//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab3.ReferenciaMediaDeHoras {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaMediaDeHoras.ServicioMediaDeHorasSoap")]
    public interface ServicioMediaDeHorasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento codigo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHorasMedias", ReplyAction="*")]
        Lab3.ReferenciaMediaDeHoras.getHorasMediasResponse getHorasMedias(Lab3.ReferenciaMediaDeHoras.getHorasMediasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHorasMedias", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab3.ReferenciaMediaDeHoras.getHorasMediasResponse> getHorasMediasAsync(Lab3.ReferenciaMediaDeHoras.getHorasMediasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHorasMediasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHorasMedias", Namespace="http://tempuri.org/", Order=0)]
        public Lab3.ReferenciaMediaDeHoras.getHorasMediasRequestBody Body;
        
        public getHorasMediasRequest() {
        }
        
        public getHorasMediasRequest(Lab3.ReferenciaMediaDeHoras.getHorasMediasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHorasMediasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string codigo;
        
        public getHorasMediasRequestBody() {
        }
        
        public getHorasMediasRequestBody(string codigo) {
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHorasMediasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHorasMediasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Lab3.ReferenciaMediaDeHoras.getHorasMediasResponseBody Body;
        
        public getHorasMediasResponse() {
        }
        
        public getHorasMediasResponse(Lab3.ReferenciaMediaDeHoras.getHorasMediasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHorasMediasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getHorasMediasResult;
        
        public getHorasMediasResponseBody() {
        }
        
        public getHorasMediasResponseBody(int getHorasMediasResult) {
            this.getHorasMediasResult = getHorasMediasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioMediaDeHorasSoapChannel : Lab3.ReferenciaMediaDeHoras.ServicioMediaDeHorasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMediaDeHorasSoapClient : System.ServiceModel.ClientBase<Lab3.ReferenciaMediaDeHoras.ServicioMediaDeHorasSoap>, Lab3.ReferenciaMediaDeHoras.ServicioMediaDeHorasSoap {
        
        public ServicioMediaDeHorasSoapClient() {
        }
        
        public ServicioMediaDeHorasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMediaDeHorasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMediaDeHorasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMediaDeHorasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab3.ReferenciaMediaDeHoras.getHorasMediasResponse Lab3.ReferenciaMediaDeHoras.ServicioMediaDeHorasSoap.getHorasMedias(Lab3.ReferenciaMediaDeHoras.getHorasMediasRequest request) {
            return base.Channel.getHorasMedias(request);
        }
        
        public int getHorasMedias(string codigo) {
            Lab3.ReferenciaMediaDeHoras.getHorasMediasRequest inValue = new Lab3.ReferenciaMediaDeHoras.getHorasMediasRequest();
            inValue.Body = new Lab3.ReferenciaMediaDeHoras.getHorasMediasRequestBody();
            inValue.Body.codigo = codigo;
            Lab3.ReferenciaMediaDeHoras.getHorasMediasResponse retVal = ((Lab3.ReferenciaMediaDeHoras.ServicioMediaDeHorasSoap)(this)).getHorasMedias(inValue);
            return retVal.Body.getHorasMediasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab3.ReferenciaMediaDeHoras.getHorasMediasResponse> Lab3.ReferenciaMediaDeHoras.ServicioMediaDeHorasSoap.getHorasMediasAsync(Lab3.ReferenciaMediaDeHoras.getHorasMediasRequest request) {
            return base.Channel.getHorasMediasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab3.ReferenciaMediaDeHoras.getHorasMediasResponse> getHorasMediasAsync(string codigo) {
            Lab3.ReferenciaMediaDeHoras.getHorasMediasRequest inValue = new Lab3.ReferenciaMediaDeHoras.getHorasMediasRequest();
            inValue.Body = new Lab3.ReferenciaMediaDeHoras.getHorasMediasRequestBody();
            inValue.Body.codigo = codigo;
            return ((Lab3.ReferenciaMediaDeHoras.ServicioMediaDeHorasSoap)(this)).getHorasMediasAsync(inValue);
        }
    }
}
